#!/usr/bin/env node
/**
 * Content gate for the new games.
 *
 * The schema rules live in `src/arcade/content.ts` and are exercised by `*.test.ts` beside each
 * pack. This script does NOT reimplement them — a second copy of a rule is the drift bug we keep
 * finding in this codebase (a hub that advertised seven modes for a game with thirteen; defaults
 * that promised a speed bonus with no clock). It runs the real validator through vitest, then
 * reads the packs itself only for the things a test cannot express: a human-readable inventory,
 * and the fact-check list of every value that is an estimate rather than a sourced figure.
 *
 *   node scripts/validate-content.mjs            check, print a summary
 *   node scripts/validate-content.mjs --report   also write docs/overnight/unverified.md
 */

import { spawnSync } from 'node:child_process';
import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CONTENT_DIRS = ['src/data/price', 'src/data/hilo'];

function loadPacks() {
  const packs = [];
  for (const dir of CONTENT_DIRS) {
    const abs = join(ROOT, dir);
    if (!existsSync(abs)) continue;
    for (const file of readdirSync(abs).filter((f) => f.endsWith('.json'))) {
      try {
        const pack = JSON.parse(readFileSync(join(abs, file), 'utf8'));
        packs.push({ file: `${dir}/${file}`, pack });
      } catch (err) {
        console.error(`✗ ${dir}/${file} is not valid JSON: ${err.message}`);
        process.exitCode = 1;
      }
    }
  }
  return packs;
}

const packs = loadPacks();
if (packs.length === 0) {
  console.error('✗ no content packs found — expected JSON under ' + CONTENT_DIRS.join(' or '));
  process.exit(1);
}

// The schema gate: the real validator, run where it lives.
console.log('Running the content schema tests…\n');
const result = spawnSync('npx', ['vitest', 'run', ...CONTENT_DIRS.filter((d) => existsSync(join(ROOT, d)))], {
  cwd: ROOT,
  stdio: 'inherit',
  encoding: 'utf8',
});
if (result.status !== 0) {
  console.error('\n✗ content failed schema validation (see the test output above)');
  process.exit(1);
}

// Inventory and provenance, which the tests assert but do not print.
let total = 0;
let unverified = 0;
const rows = [];
const factCheck = [];

for (const { file, pack } of packs) {
  const items = Array.isArray(pack.items) ? pack.items : [];
  const bad = items.filter((i) => !i.verified);
  total += items.length;
  unverified += bad.length;
  rows.push({
    pack: pack.id ?? '?',
    file,
    items: items.length,
    unverified: bad.length,
    unit: pack.unit ?? '?',
  });
  for (const i of bad) {
    factCheck.push({ pack: pack.id, id: i.id, name: i.name, value: i.value, unit: i.unit, source: i.source, asOf: i.asOf });
  }
}

console.log('\nContent inventory');
const width = Math.max(...rows.map((r) => r.pack.length), 4);
for (const r of rows) {
  const flag = r.unverified === r.items ? 'ALL ESTIMATED' : r.unverified > 0 ? `${r.unverified} estimated` : 'all sourced';
  console.log(`  ${r.pack.padEnd(width)}  ${String(r.items).padStart(4)} items  ${r.unit.padEnd(7)} ${flag}`);
}
console.log(`\n  ${total} values, ${unverified} estimated, ${total - unverified} sourced`);

if (process.argv.includes('--report')) {
  const out = join(ROOT, 'docs/overnight/unverified.md');
  mkdirSync(dirname(out), { recursive: true });
  const lines = [
    '# Values to fact-check',
    '',
    `Generated by \`scripts/validate-content.mjs\`. ${factCheck.length} of ${total} values are`,
    'author estimates rather than sourced figures. Every one is listed here so it can be checked',
    'or replaced; nothing in the app presents these as sourced data.',
    '',
    '| Pack | Item | Value | Unit | As of | Source |',
    '| --- | --- | ---: | --- | --- | --- |',
    ...factCheck.map(
      (f) => `| ${f.pack} | ${f.name} | ${f.value} | ${f.unit} | ${f.asOf} | ${f.source} |`,
    ),
    '',
  ];
  writeFileSync(out, lines.join('\n'));
  console.log(`\n  wrote ${factCheck.length} rows to docs/overnight/unverified.md`);
}

console.log('\n✓ content is valid');
